### ISSUE TITLE
Postgres outputs non-javascript-compatible JSON

### ISSUE THREAD

**Issue by SohumB** [brianc/node-pg-types#10]
```javascript
knex.raw('select row_to_json(row(1111111111111111111::bigint)) as example;')
  .then(function(res) { console.log(res.rows[0].example); });
// outputs { f1: 1111111111111111200 }
```

That is, postgres doesn't account for javascript's type limits when outputting its json, and `node-pg-types` can't use its logic for defaulting those types to string, because it just sees that json is coming down the wire. This affects at least bigints and arbitrary-precision numbers, possibly more things. 

What do we do? Can we do anything?

**Comment by bendrucker** [comment]
Yup, no dice here other than using a custom JSON parser
