### ISSUE TITLE
Parse array of BigInt

### ISSUE THREAD

**Issue by s888** [brianc/node-pg-types#111]
Hi,
I have a column of type ```bigint[]```
But in response, it is converted to an array of string.

How do I parse it?
This works when the column is of type bigint
```
import { types } from "pg"
types.setTypeParser(20, BigInt); 
```
Tried this but it gives an error.
```
import { Client, types } from "pg"
types.setTypeParser(1016, str => types.arrayParser(str,BigInt));
```

**Comment by bendrucker** [comment]
What error?

**Comment by sehrope** [comment]
Must be that `arrayParser(...)` is no longer re-exported: https://github.com/brianc/node-pg-types/commit/09ea6256a4addca199d45db850e59ce50e330d34#diff-168726dbe96b3ce427e7fedce31bb0bcL3

Try something like this to use it directly from the `postgres-array` package:
```js
const { types } = require('pg')
const pgArray = require('postgres-array')
types.setTypeParser(1016, text => pgArray.parse(text, BigInt))
```

**Comment by bendrucker** [comment]
Good catch, thanks!
