### ISSUE TITLE
please throw when oid is nullish

### ISSUE THREAD

**Issue by kapouer** [brianc/node-pg-types#128]
Hi

i just had a hard time debugging a stupid mistake:
```
pg.types.setTypeParser(
  pg.types.builtins.TIMESTAMPZ,
  str => myDateParser(str)
);
```

which silently fails to call myDateParser.
Can you spot the mistake ?
It took me a while to get it... so i think it would be nice if `setTypeParser(null, ...)` threw an error.

**Comment by bendrucker** [comment]
Totally reasonable, a PR would be appreciated/merged
