### ISSUE TITLE
Releasing the latest changes

### ISSUE THREAD

**Issue by mwanago** [brianc/node-pg-types#131]
If I see correctly, the latest version of [pg-types](https://www.npmjs.com/package/pg-types) has been released in August of 2020. Since then, there were a few notable changes merged to the master branch. Can we release a new version including those?

**Comment by henrinormak** [comment]
Any updates to this, is there a reason for not publishing the latest state as a version?

Wondering when the latest changes from this package might trickle down into [`pg`](https://github.com/brianc/node-postgres/blob/master/packages/pg/package.json#L28)

**Comment by brianc** [comment]
my bad I can publish a new version today! Releasing this into core pg i think involves a few backwards incompatible changes I'll need to check out, but should be doable very 🔜

**Comment by bendrucker** [comment]
I also forgot about this. 😬 The breaking changes should generally be breaking behavioral changes, worth noting in the changelog, but AFAIK there's no API changes that would break the way `pg` depends on this package.
