### ISSUE TITLE
Is the Date parsing fix in the current pg release?

### ISSUE THREAD

**Issue by jcamato** [brianc/node-pg-types#138]
I found https://github.com/brianc/node-pg-types/issues/50 because I noticed my Postgres DATE columns were returning as `'yyyy-MM-ddThh:mm:ss.mssZ'` instead of `'yyyy-MM-dd'`. It looks like the fix https://github.com/brianc/node-pg-types/pull/121 by @ianwalter was merged almost two years ago, but I am still encountering this date parsing issue on pg 8.7.3 and node 14.18.3. 

Currently I am using the workaround mentioned in the first issue
```js
// Prevent node-postgres from converting Postgres DATE type
pg.types.setTypeParser(1082, function (value) {
  return value;
});
```

**Comment by bendrucker** [comment]
`pg` no but this package yes. If you'd like to discuss upgrading the types in a pg release you can open an issue there or a PR.
