### ISSUE TITLE
Entries of type DATE are converted from UTC to local date

### ISSUE THREAD

**Issue by Verdier** [brianc/node-pg-types#19]
Postgresql DATE are stored in the following format `yyyy-MM-dd` in UTC (following the SQL convention) but are converted by the `parseDate` function in local date considering that the timezone is missing.

```javascript
      //it is a date in YYYY-MM-DD format
      //add time portion to force js to parse as local time
      return new Date(isoDate + ' 00:00:00');
```

That result in offsetting (depending on the local timezone) the stored date. The DATE entry should be considered as **UTC date**.

**Comment by steve-p-com** [comment]
I'm having this same issue today, after we switched to DST yesterday. I have PostgreSQL tables containing server logs with a type ```date``` which is always UTC. Unfortunately the node server that I use to view the logs does not work anymore, because this ```date``` type is being incorrectly converted to local time, whereas it should be UTC.

**Comment by Verdier** [comment]
The workaround we use is to run our server script in UTC. Just use `TZ=UTC node app.js`.

**Comment by steve-p-com** [comment]
Why didn't I think of that. Seems to be working great, thanks.

**Comment by vitaly-t** [comment]
That's strange. I've used the UTC format in pg-promise from day one, and nobody ever complained.

And looking at the PG's own implementation of it, I do wonder why use such complexity in the first place...

from lib/utils.js
```javascript
function dateToString(date) {
  function pad(number, digits) {
    number = ""+number;
    while(number.length < digits)
      number = "0"+number;
    return number;
  }

  var offset = -date.getTimezoneOffset();
  var ret = pad(date.getFullYear(), 4) + '-' +
    pad(date.getMonth() + 1, 2) + '-' +
    pad(date.getDate(), 2) + 'T' +
    pad(date.getHours(), 2) + ':' +
    pad(date.getMinutes(), 2) + ':' +
    pad(date.getSeconds(), 2) + '.' +
    pad(date.getMilliseconds(), 3);

  if(offset < 0) {
    ret += "-";
    offset *= -1;
  }
  else
    ret += "+";

  return ret + pad(Math.floor(offset/60), 2) + ":" + pad(offset%60, 2);
}
```

**Comment by jacott** [comment]
This is what I do for a work around:

```javascript
// timestamp without zone
pgTypes.setTypeParser(1114, 'text', function (value) {
  return new Date(value+'Z');
});
```

**Comment by bendrucker** [comment]
I looked in the PG docs for anything about this and came up empty. If someone can find a source that says dates should be interpreted as UTC, we can implement this differently.

**Comment by jacott** [comment]
From the http://www.postgresql.org/docs/9.4/static/datatype-datetime.html spec in section 8.5.3. Time Zones it says
  "PostgreSQL assumes your local time zone for any type containing only date or time."

So I think pg-types dos the right thing.

**Comment by jacott** [comment]
I now longer use my work around above; I setenv TZ=UTC before starting node instead.

**Comment by vitaly-t** [comment]
[Section 8.5.1.3](http://www.postgresql.org/docs/9.4/static/datatype-datetime.html#AEN5989) gives a better explanation, so basically, UTC is the way to go. And this is what I've always been using, with method `Date.toUTCString`

**Comment by bendrucker** [comment]
Please quote the text you think supports parsing as UTC

**Comment by vitaly-t** [comment]
*For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as Greenwich Mean Time, GMT). An input value that has an explicit time zone specified is converted to UTC using the appropriate offset for that time zone. If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's TimeZone parameter, and is converted to UTC using the offset for the timezone zone.*

**Comment by brianc** [comment]
@vitaly-t the node-postgres team and various contributors have had this conversation multiple times years ago, committed to a direction, made the backwards incompatible changes necessary, and there is no going back. The issue has been decided to be the way it is currently behaving. The good news is, and somewhat the reason this module exists stand alone, is if you don't agree with how it acts you can easily override the date parser in your own applications!  That way everyone wins.  As far as the team is concerned though the discussions around this have been had and the decision has been made.
