### ISSUE TITLE
Register parser for type time[]

### ISSUE THREAD

**Issue by Americas** [brianc/node-pg-types#32]
Hi, I was having trouble with parsing time arrays and found that the problem is easily solvable by adding a small line of code to `lib/textParsers.js`. In the init function, just add:

```javascript
  register(1183, parseStringArray); // time[]
```

I would do a pull request, but it seems so much trouble for such a simple change.

**Comment by bendrucker** [comment]
Please send a pull request! It would be really appreciated.
