### ISSUE TITLE
select count(*) as c from users returns type "string"

### ISSUE THREAD

**Issue by bf** [brianc/node-pg-types#39]
First of all thanks for this nice project. I am experiencing an issue where I use `count(*)` in a query and I get the value "2" returned, which is represented as a Javascript string.

An explicit typecast fixes the problem, but I am afraid that many more of these bugs might occur in the project. As this issue came up overnight, I am unsure where to search the culprit of this problem.

I have written test cases using db.connect -> db.query -> typeof result.rows[0].c === "number", and found out that only count(*) raises this issue. I am using `pg` version 4.4.1.

**Comment by bendrucker** [comment]
This is not a bug. Take a look at the postgres docs on the types of the aggregate functions:

http://www.postgresql.org/docs/9.4/static/functions-aggregate.html

You'll see that count is a bigint. node-postgres can't auto-parse that for you without loss of precision. If you know that your counts are small enough, you can safely parse it in your application code.

**Comment by bf** [comment]
This issue appeared overnight and created failing comparisons like `count === 2` which now needs to be either SQL-typecasted or `parseInt(count, 10) === 2`. I know about bigint conversion problems but in my case this issue arose in a mature project without me changing much before.

Now I am stuck trying to figure out if a postgres update caused this behavior, or some hidden node-pg update, or.. ?

**Comment by bendrucker** [comment]
No idea what changed in your setup but this has been the behavior in node-postgres for a long time, well over a year if memory serves.

**Comment by bf** [comment]
Okay, thanks for the clarification. This lets me rule out a change in the node-pg modules. I still cannot wrap my head around this issue.
