### ISSUE TITLE
Parser for citext[]

### ISSUE THREAD

**Issue by joskuijpers** [brianc/node-pg-types#41]
Hi!

I am missing a `citext[]` parser, which can be parsed exactly like `text[]`. Currently I use a workaround by casting my function result from `citext[]` to `text[]`, but it is nasty and I don't like it.
I wouldn't mind creating a pull request but I have no clue how to retrieve the type-number.

Thanks a lot,

Jos

**Comment by bendrucker** [comment]
Instructions for getting the OID are in the readme!

**Comment by joskuijpers** [comment]
@bendrucker Thanks
58398 it is :D
I'll implement it.

**Comment by joskuijpers** [comment]
I implemented it locally. It would be a lot cleaner inside this library (just 1 line of code), but I don't know if that is wanted.

**Comment by bendrucker** [comment]
Please send a PR!

**Comment by joskuijpers** [comment]
@bendrucker This is fun. After a reinstall of my pg server, the OID of citext changed... On another machine, the OID is álso different. 
Did I tell you that CITEXT an extension is?

**Comment by bendrucker** [comment]
Ah okay if it's not consistent it's a no go unfortunately

**Comment by hi2u** [comment]
Just wondering how people might have solved this problem in their projects?

I'm using Knex + pg, and just ran into this issue of CITEXT[] values coming back as strings.  And yeah, looks like the `OID` differs on different servers.

Any solutions to this that people have come up with? (might be outside the scope of this package, but seems as good place to discuss it than anywhere else)
