### ISSUE TITLE
README contains wrong OIDs for time types

### ISSUE THREAD

**Issue by joskuijpers** [brianc/node-pg-types#42]
The timestamp and timestamptz oids are reversed on the README page.

```sql
select typname, oid, typarray from pg_type where typtype = 'b' and typname LIKE 'timestamp%' order by oid
```
```
"timestamp";1114;1115
"timestamptz";1184;1185
```

**Comment by bendrucker** [comment]
PR would be much appreciated

**Comment by joskuijpers** [comment]
Sure but it is actually easier for Brian to just click the edit button than to do checks and merges. That is why I just said it :p

**Comment by bendrucker** [comment]
Fixed. In the future PRs are always appreciated and fastest, no matter how small the change is!
