### ISSUE TITLE
Parsing postgres intervals in ISO 8601 format

### ISSUE THREAD

**Issue by nareshbhatia** [brianc/node-pg-types#44]
I am using `moment.duration` as the internal format for intervals in my application. What would be the most direct way of saving and restoring intervals in the ISO 8601 format?

1. What are the steps to override the pg-types parse and format functions for Interval? (I am new to pg-types).
2. How do I force postgres to output ISO 8601 intervals programmatically (equivalent to the command `SET intervalStyle = iso_8601`).

**Comment by nareshbhatia** [comment]
Please advise if I should be asking this question elsewhere.

**Comment by bendrucker** [comment]
Here's fine. There's no formatting built in that you override. You'd do that in your application code. For parsing, take a stab at duplicating the example in the docs and amending it for your app:

https://github.com/brianc/node-pg-types#use

When you spin up your Postgres connections you can run that command, is that what you're looking for?

**Comment by nareshbhatia** [comment]
Thanks, @bendrucker. I will try that.

For the second question, yes I would like to set up the Postgres connection to always return intervals in ISO 8601 format. On the psql command line, I do this using:

```
SET intervalStyle = iso_8601;
```

How do I do the same programmatically? I am using knex to establish my connections:

```
var pg = require('knex')({
  client: 'pg',
  connection: {
    ...
  }
});
```

**Comment by bendrucker** [comment]
You can use `afterCreate` on the connection pool to run this query when every connection is acquired:

https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/test/knexfile.js#L12

**Comment by nareshbhatia** [comment]
Awesome! Thanks.
