### ISSUE TITLE
null won't be passed into parser

### ISSUE THREAD

**Issue by aleung** [brianc/node-pg-types#46]
In readme, the example says:

``` js
var types = require('pg').types
types.setTypeParser(20, function(val) {
  //remember: all values returned from the server are either NULL or a string
  return val === null ? null : parseInt(val)
})
```

I want to make a parser to convert NULL data in pg JSON type to something other. But test shows that if a field is NULL, it won't be passed into parser. I read the code and find in [result.js#L78](https://github.com/brianc/node-postgres/blob/master/lib/result.js#L78), parser is invoked only if raw data is not NULL.

**Comment by bendrucker** [comment]
Why should the parser allow that?

**Comment by aleung** [comment]
@bendrucker 

It's a design decision. 

In my use case, if it's allowed, then I can write a parser to convert NULL into something that I want, rather than check every time where a query is returned.

If it isn't intended to allow, please update the document to let users not expect null to be passed into parser.

**Comment by aleung** [comment]
It'll be good to update the example to remove testing null:

``` js
var types = require('pg').types
types.setTypeParser(20, function(val) {
  //remember: all values returned from the server are either NULL or a string, NULL is not parsed
  return parseInt(val)
})
```
