### ISSUE TITLE
Could you please make a new pg-types release?

### ISSUE THREAD

**Issue by kzc** [brianc/node-pg-types#47]
so that the `pg` module can pick up the `pg-types` browserify fix in https://github.com/brianc/node-pg-types/commit/d240e961a36db90709ebf260d9d9cb1358e33e91

**Comment by bendrucker** [comment]
@brianc

**Comment by brianc** [comment]
no problem! Sorry for the delay

pushing a new minor version now!

**Comment by brianc** [comment]
Published at `pg-types@1.11.0`  Thanks for the bing @bendrucker ❤️

**Comment by kzc** [comment]
gracious
