### ISSUE TITLE
Timestamptz, same point in time but different representation for same query with 'set local time zone'

### ISSUE THREAD

**Issue by fselcukcan** [brianc/node-pg-types#51]
I have an issue with representation of the timestamps with time zone on my web app due to a query result from PostgreSQL. I use `pg-promise`, which uses `node-postgres` and this library under the hood. I have code that causes the issue on the question on he SO. I make use of SQL `set local time zone`, nad I explain how I apply it. For simplicity, I just link to the question page:
[Timestamptz issue on StackOverflow](http://stackoverflow.com/questions/39259916/timestamptz-same-point-in-time-but-different-representation-for-same-query-with).

**Comment by bendrucker** [comment]
Do you think you can post a more concise summary of the issue here?

**Comment by isikfsc** [comment]
Here we go;

I am trying to build my web app that will store the data on a PostgreSQL database server running on some location on Earth and will have users connecting from other locations, so probably different timezones and offsets than my servers.

I need to show the dates and times of the actions like, posts created, posts edited, comments submitted, etc. according to the each connecting user. This is just like the StackExchange. However I am running into problems of timezones and offsets as described as follows:

Everything seems working correct in my *pgAdmin3 SQL Editor*. When I write the query below in *pgAdmin3 SQL Editor* with `set local time zone 'Europe/Oslo'`, for example, I get both the `posts` and `tags` table `created_at` fields correct with `+2` offset in the output. In the output row, the `created_at` field of `posts` table is `2016-08-29 19:15:53.758+02` and for same row `created_at` for `tags` table is `2016-08-29T19:15:53.758+02:00`.

**However**, when I put it in a *route function* in my *Nodejs* *Express.js* server with *pg-promise* as the connection lib, I only get the `tags` table `created_at` field correct with the time in `Oslo` with timezone offset appended as expected, I get `created_at` field of the `posts` table in `UTC` not as expected.

All *timestamps* are defined as `timestamp(3) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP` as shown below. Also, without the setting `set local time zone`, I get the same behaviour, for first table I get `UTC` time, for the latter I get timestamp with offset of server appended.

Does not the `set local time zone` directive bind all the query? What is the missing point in my approach?

an example query I use:

    select
        q.*, -- created_at timestamp (with time zone) is one of those columns
        u.name as author,
        u.reputation,
        case when count(t.*)=0 then '[]' e json_agg(t.*) end as tags
    from posts q
    
    -- authors
    join users u
    on q.author_id = u.id
    
    -- tags
    left join post_has_tag p_h_t
    on q.id = p_h_t.post_id
    left join tags t
    on p_h_t.tag_id = t.id
    
    where q.post_type = 'question'
    group by q.id, u.id;

An example express.js route function:

    trialRoutes.get('/x', function (req, res) {
		db.query(
			`
			--begin;
			SET LOCAL TIME ZONE 'Europe/Oslo';
			SELECT
			    q.*, -- created_at timestamp (with time zone) is already in here
			    u.name AS author,
			    u.reputation,
			    CASE WHEN count(t.*)=0 THEN '[]' ELSE json_agg(t.*) END as tags
			FROM posts q

			-- authors
			JOIN users u
			ON q.author_id = u.id

			-- tags
			left join post_has_tag p_h_t
			on q.id = p_h_t.post_id
			left join tags t
			on p_h_t.tag_id = t.id

			WHERE q.post_type = 'question'
			group by q.id, u.id;
			--commit;
			`
		)
			.then(function (data) {
				res.json(data)
			})
			.catch(function (error) {
				console.log("/login, database quesry error.", error);
			});
	})

The result I get from *Express.js* http server with *pg-promise*. Note the different timestamps that actually should point same point in UTC, which is correctly done, and representation which is not correctly done:


    [
      {
        "id": "7",
        "created_at": "2016-08-29T21:02:04.153Z", // same point in time, different representation
        "title": "AAAAAAAAAAA",
        "text": "aaaaa aaaaaaa aaaaaa",
        "post_url": "AAAAAAAAAAA",
        "score": 0,
        "author_id": 1,
        "parent_post_id": null,
        "post_type": "question",
        "is_accepted": false,
        "acceptor_id": null,
        "timezone": "2016-08-29T20:02:04.153Z",
        "author": "Faruk",
        "reputation": 0,
        "tags": [
          {
            "id": 4,
            "created_at": "2016-08-29T23:02:04.153+02:00", // same point in time, different representation
            "label": "physics",
            "description": null,
            "category": null
          }
        ]
      },
      {
        "id": "6",
        "created_at": "2016-08-29T17:24:10.151Z",
        "title": "Ignoring timezones altogether in Rails and PostgreSQL",
        "text": "Ignoring timezones altogether in Rails and PostgreSQL",
        "post_url": "Ignoring-timezones-altogether-in-Rails-and-PostgreSQL",
        "score": 0,
        "author_id": 2,
        "parent_post_id": null,
        "post_type": "question",
        "is_accepted": false,
        "acceptor_id": null,
        "timezone": "2016-08-29T16:24:10.151Z",
        "author": "Selçuk",
        "reputation": 0,
        "tags": [
          {
            "id": 3,
            "created_at": "2016-08-29T19:24:10.151+02:00",
            "label": "sql",
            "description": null,
            "category": null
          }
        ]
      }
    ]


The definition of the `posts` and `tags` tables used here:

    -- questions and answers
    CREATE TABLE posts
    (
      id bigserial PRIMARY KEY,
      created_at timestamp(3) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      
      title character varying(100),
      text text,
      post_url character varying(100),
      
      score integer DEFAULT 0,
      author_id integer NOT NULL REFERENCES users (id),
      parent_post_id integer REFERENCES posts (id),
      post_type varchar(30),
      
      is_accepted boolean DEFAULT FALSE,
      acceptor_id integer REFERENCES users (id) DEFAULT NULL
      --seen_by_parent_post_author boolean DEFAULT false
      
      --view_count
      --accepted_answer_id
      --answer_count
    );

    CREATE TABLE tags
    (
        id bigserial PRIMARY KEY,
        created_at timestamp(3) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        label character varying(30) NOT NULL,
    	description character varying(200),
    	category character varying(50)
    );

**Comment by bendrucker** [comment]
Thanks but copying and pasting the whole thing wasn't what I had in mind. I was hoping you'd cut out all of the unnecessary parts so I can more quickly scan through the queries.

**Comment by isikfsc** [comment]
:) First of all I have thought wee need the all case explanation here for quick access.
Secondly, you have written if I can post a more **concise** post:

>Do you think you can post a more **concise** summary of the issue here?

not a more **compact** post, though **concise** also need to be in few words.

**Comment by bendrucker** [comment]
You should always get the version with the `Z` suffix for UTC. No matter what timezone you set it's parsed into a `Date` and `Date.prototype.toJSON` will always return that way. Is it possible the joined field isn't getting logged at all? Try logging out the `constructor` property of that value.
