### ISSUE TITLE
numeric parsed as a string : is this the expected behaviour ?

### ISSUE THREAD

**Issue by abenhamdine** [brianc/node-pg-types#52]
Hi folks, and thanks for this module,

I'm currently using node-postgres 5.1, which uses pg-types 1.11
When I query a table with a numeric(5.2) column (oid 1700), I get the result as a string.
Eg : '2.00' though I was expecting 2 (number)

Is this the expected result ? 
If yes, shouldn't the docs updated, as for big ints ?

Shoud I have to set my own parser for oid 1700 ?

Thx in advance.

**Comment by bendrucker** [comment]
1700 should be a number (https://github.com/brianc/node-pg-types/blob/5f379d2fe88725e57237999b4a2c2f3769e6a99d/lib/binaryParsers.js#L129) for sure. Can you double check that your column is that type?

https://www.postgresql.org/docs/current/static/datatype-oid.html

**Comment by abenhamdine** [comment]
Yes, I've checked with the following query:
```sql
select attname, atttypid from pg_attribute
where attrelid = 'myTable'::regclass and attname = 'myColumn';
```
 and the atttypid of 'myColumn' is definitely 1700.

Could this be a bug in node-postgres rather than in node-pg-types ?

**Comment by bendrucker** [comment]
Actually I misread the source. Here's the test:

https://github.com/brianc/node-pg-types/blob/5f379d2fe88725e57237999b4a2c2f3769e6a99d/test/types.js#L43-L50

numeric should be returned as a string:

> The type numeric can store numbers with a very large number of digits and perform calculations exactly. It is especially recommended for storing monetary amounts and other quantities where exactness is required. However, arithmetic on numeric values is very slow compared to the integer types, or to the floating-point types described in the next section.

https://www.postgresql.org/docs/9.3/static/datatype-numeric.html

**Comment by abenhamdine** [comment]
Ah yes, I saw the test too.
Are you open to a PR to update the docs in order to clarify this ?

**Comment by bendrucker** [comment]
Happy to review a PR. The thinking behind the bigint example is that it's returned from the `count` and so a lot of people encounter it without realizing and without ever using a non-JS-safe type in their schema. That wouldn't be true of this case but if you can find a concise way to note it we can add something.

**Comment by abenhamdine** [comment]
For the future reader : in postgres, sum aggregate function determine its type as followin (per docs https://www.postgresql.org/docs/current/static/functions-aggregate.html) : 


> bigint for smallint or int arguments, numeric for bigint arguments, otherwise the same as the argument data type

So even if you don't expect bigints or numerics from you db, you are likely to get ones soon or late if you use sum() and you should probably cast bigint and numerics as explained in the readme of this repo
