### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by chamini2** [brianc/node-pg-types#57]
The [https://www.npmjs.com/package/pg-types](npm) package has not been released in 11 months. Please release the latest version 😄 .

**Comment by chamini2** [comment]
Including the merge of #59, please!

**Comment by chamini2** [comment]
Hello, I'm bumping this because we would really appreciate a release! 😄

**Comment by melloc** [comment]
I'd also like to echo this. Could a new release with the latest changes to node-pg-types be published to npm so that they can be pulled in with node-postgres? Thanks!

**Comment by chamini2** [comment]
@brianc, maybe you are not getting notifications since you are not watching this repo?

**Comment by brianc** [comment]
oh my bad!

**Comment by brianc** [comment]
so sorry about that - added this repo back to watching. :eye: Gonna push to npm right this second!

okay pushed `pg-types@1.12.0`

**Comment by chamini2** [comment]
Thanks!
