### ISSUE TITLE
Error message undefined

### ISSUE THREAD

**Issue by houssemDevs** [brianc/node-pg-types#74]
Hi,

I am using pg to execute a stored procedure on postegres 10, this procedure may fail and raise an exception, the exception message can not be extracted from the error (err.error 'undefined'), but can be logged on the console.
when I log the error (`console.log(err);`) I see the exception message along with the stack trace, but when I log only the error message (`console.log(err.error)`) I get undefined.
```
let query = {
    text: 'SELECT insert_events($1, $2, $3, $4, $5)',
    values: [provider, type, events, types, expectedVersion],
  };
  const qfunc = async () => {
    const cnn = await pool.connect();
    try {
      const res = await cnn.query(query);
      return res.rows[0].insert_events;
    } catch (err) {
      console.log('Error : ', err.where);
      throw err;
    } finally {
      cnn.release();
    }
  };
  return qfunc();
```

**Comment by charmander** [comment]
The property for the message associated with an Error object in JavaScript is `err.message`, not `err.error`.

**Comment by charmander** [comment]
The word “error:” there is part of the error message. It’s not a property.

**Comment by houssemDevs** [comment]
I am not sure but when I use err.message as you suggested I get the message "Concurrency problem ...... ".
But the issue is solved thank you.

**Comment by houssemDevs** [comment]
I will close the issue. Thank you for your help.
