### ISSUE TITLE
Doc- types.builtins.NUMERIC usage

### ISSUE THREAD

**Issue by billreynolds007** [brianc/node-pg-types#87]
One example in the readme.md is
   types.setTypeParser(types.builtins.TIMESTAMPTZ, parseFn)

This approach
   var types = require('pg').types;
   types.setTypeParser(types.builtins.NUMERIC, function(val) { return parseFloat(val); });

 shows an error
   Cannot read property 'NUMERIC' of undefined

**Comment by billreynolds007** [comment]
I ended up doing
    npm install pg-types

And then, 
    var types = require('pg').types;
    var pgTypes = require('pg-types');

The 2nd line automatically installs converters. So this line is not necessary
types.setTypeParser(pgTypes.builtins.NUMERIC, function(val) { return parseFloat(val); });

**Comment by charmander** [comment]
This was also fixed in pg@7.12.1 by brianc/node-postgres#1937.

**Comment by curiousercreative** [comment]
sounds like this issue should be closed?
