### ISSUE TITLE
Binary array unknown ElementType log vs Error

### ISSUE THREAD

**Issue by sehrope** [brianc/node-pg-types#93]
While going through for adding linting I noticed the log line at 200: https://github.com/brianc/node-pg-types/blob/10f2725d6133cae1a09a52e1a09305747e66fb16/lib/binaryParsers.js#L188-L202

Should be a `throw new Error(...)` right? At the very least something should be returned as now it'd default to returning `undefined`.

**Comment by bendrucker** [comment]
Agreed, there's no reason why a library like this should be printing anything to std{out,err}

**Comment by charmander** [comment]
Yep! Although nothing throws explicitly so far, there are plenty of implicit throws, and silently giving the wrong result seems worse.
