### ISSUE TITLE
Wrong and too strict TS type definitions

### ISSUE THREAD

**Issue by stekycz** [brianc/node-pg-types#98]
TS type definitions were [added recently](https://github.com/brianc/node-pg-types/commit/8e73b4645e7d26f9d91f195c63fdf98a0a1decb7) in version 2.2.0.

However, there is already an existing [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg-types/index.d.ts) version of them.

They are different and definitely typed version is better to use for us. ISo I would suggest merge of them together.

Differences (issues in new type definitions):

1. Missing `TypeParser` type for parsing function
2. Too strict `oid: TypeId` which does not allow custom DB types which might have any number
3. Wrong `arrayParser` type definition that does not respect the implementation (Definitely Typed definition does)

**Comment by bendrucker** [comment]
All sounds valid, would really appreciate a PR!

**Comment by stekycz** [comment]
@bendrucker Created. I have tried to prepare the best definition of types possible that matches the implementation fully.
